[build]
publish = "frontend/build"
# Default build command.
command = "pnpm run build -w frontend"

[functions]
directory = "frontend/functions/"

[context.dev.functions]
directory = "frontend/functions/"